apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-struts
  namespace: apache-struts
  labels:
    app: apache-struts
    demo: roadshow
    repo: demo-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache-struts
  template:
    metadata:
      labels:
        app: apache-struts
        demo: roadshow
        repo: demo-apps
    spec:
      containers:
        - name: apache-struts
          image: quay.io/mfoster/apache-struts:0.1.0
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"

