# Deployment named "varnish"
# Listens on :8080
apiVersion: apps/v1
kind: Deployment
metadata:
  name: varnish
  namespace: backend
  labels:
    app: varnish
    demo: roadshow
    repo: demo-apps
spec:
  replicas: 1
  selector:
    matchLabels:
       app: varnish
  template:
    metadata:
     labels:
       app: varnish
       demo: roadshow
       repo: demo-apps
    spec:
      imagePullSecrets:
      - name: rhacs-demo-pull-pull-secret
      containers:
      - image: quay.io/rhacs-demo/netflow:latest
        command: ["/bin/entrypoint"]
        args: ["-listen", "8080", "-connect", "api-server-service.backend.svc.cluster.local:9001"]
        imagePullPolicy: Always
        name: varnish
        ports:
        - containerPort: 8080
          protocol: TCP

