apiVersion: v1
kind: Namespace
metadata:
  name: dvwa-hummingbird
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dvwa-hummingbird
  namespace: dvwa-hummingbird
  labels: 
    demo: roadshow
    repo: demo-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dvwa-hummingbird
  template:
    metadata:
      labels:
        app: dvwa-hummingbird
        demo: roadshow
        repo: demo-apps
    spec:
      containers:
        - name: dvwa-hummingbird
          image: quay.io/mfoster/dvwa-hummingbird:0.1.0
          command: ["/bin/bash", "-c", "while true; do sleep 1000; done"]
          stdin: true
          tty: true
